Translation improvements
theforeman/hammer-cli-foreman-ansible pull request #17
Opened 2023-05-10 12:49 UTC by stejskalleos

* Extract missing strings for the translations
* Update config for the transifex-cli
* Update *.po files
* Fix interpolations in strings

2023-05-17 13:09 UTC, ekohl approved these changes
It should be noted that right now no `.mo` are present. We can solve this in packaging, but don't do that today. That's still something to resolve to make the translations usable in practice.

2023-05-17 14:37 UTC, stejskalleos commented
> It should be noted that right now no `.mo` are present. We can solve this in packaging, but don't do that today. That's still something to resolve to make the translations usable in practice.

Should I add them?

2023-05-23 10:54 UTC, ekohl requested changes
I just realized all the translation files are empty. I'd leave them out until we have translations.

2023-05-23 10:54 UTC, ekohl commented on locale/cs/hammer_cli_foreman_ansible.po
> +# Czech translations for hammer_cli_foreman_ansible package.
You're adding this file, but it doesn't appear to include any translations. We normally only do this with > 50% translations.

2023-07-13 12:53 UTC, ofedoren commented
Closing in favor of https://github.com/theforeman/hammer-cli-foreman-ansible/pull/21

2023-07-13 12:53 UTC, closed without merging